## Import Pandas

In [2]:
import pandas as pd

## Read in the dataset

In [3]:
data = pd.read_csv('data-zillow.csv')
data.head()

,Date,RegionID,RegionName,State,Metro,County,SizeRank,Price
0,2017-05-31,6181,New York,NY,New York,Queens,0,672400
1,2017-05-31,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,1,629900
2,2017-05-31,17426,Chicago,IL,Chicago,Cook,2,222700
3,2017-05-31,13271,Philadelphia,PA,Philadelphia,Philadelphia,3,137300
4,2017-05-31,40326,Phoenix,AZ,Phoenix,Maricopa,4,211300

## Get Mean price for every State

In [7]:
grouped_data = data[['State', 'Price']].groupby('State').mean()
grouped_data.head()

        Price
State
AK     237783
AL     137645
AR     136331
AZ     232353
CA     617425

## Split the data into groups

In [8]:
grouped_data = data[['State', 'Price']].groupby('State')

In [9]:
list(grouped_data)

[('AK',       State   Price
  57       AK  293900
  842      AK  221000
  1793     AK  247800
  1830     AK  213100
  1974     AK  323100
  3756     AK  206500
  3869     AK  270700
  4450     AK  224700
  5229     AK  207500
  5996     AK  249700
  9622     AK  219600
  10162    AK  175800), ('AL',       State   Price
  71       AL  112100
  121      AL   61900
  154      AL  138600
  736      AL  110500
  913      AL  105700
  1010     AL  141600
  1035     AL  260300
  1254     AL   66600
  1356     AL  198300
  1577     AL  267300
  1705     AL  162100
  1961     AL   48100
  2023     AL  113200
  2109     AL  180100
  2121     AL  313900
  2157     AL   58700
  2237     AL  125300
  2268     AL  161800
  2287     AL  332900
  2393     AL  109300
  2399     AL  105900
  2410     AL   64700
  2494     AL  135700
  2659     AL  148500
  2716     AL  225400
  2789     AL  598900
  2955     AL  180800
  3060     AL  125900
  3078     AL  125700
  3112     AL  176100
  ...     ...     ...
  9768     AL  186200
  9790     AL  111800
  9794     AL  155800
  9821     AL  130400
  9857     AL  117700
  9864     AL  124100
  9866     AL   57200
  9889     AL  110400
  9903     AL  144800
  9938     AL  110300
  9960     AL  158700
  10023    AL  107300
  10037    AL  159500
  10079    AL  184300
  10114    AL  127100
  10115    AL  221800
  10155    AL  179400
  10352    AL  161900
  10362    AL   46600
  10369    AL  271000
  10370    AL  146600
  10425    AL  122800
  10464    AL   46000
  10491    AL  100300
  10504    AL   48800
  10505    AL   62700
  10608    AL  151500
  10743    AL  132700
  10790    AL   67000
  10824    AL  106200

  [149 rows x 2 columns]), ('AR',       State   Price
  129      AR  132200
  453      AR  111500
  489      AR  143800
  581      AR  133600
  588      AR   90600
  660      AR  186200
  669      AR  146600
  879      AR   72300
  987      AR  168200
  1236     AR  111100
  1317     AR   93500
  1339     AR  104600
  1647     AR  136100
  1720     AR  126500
  1819     AR  162400
  1877     AR  105400
  2067     AR  139100
  2126     AR  187700
  2416     AR  150700
  2648     AR  106500
  2728     AR   95600
  2784     AR  176300
  2816     AR  198300
  3187     AR  127400
  4590     AR  138500
  4665     AR  148300
  4694     AR   65300
  4970     AR  152200
  5531     AR  137700
  5738     AR  139900
  ...     ...     ...
  8199     AR  130400
  8368     AR  107200
  8583     AR  121200
  8634     AR  124300
  8678     AR  138000
  8690     AR  166300
  8829     AR   88800
  8876     AR  268800
  9266     AR  121900
  9639     AR  169800
  9723     AR  121600
  9863     AR  159600
  9922     AR  189000
  9992     AR  118900
  10126    AR  102400
  10185    AR  156300
  10218    AR  119700
  10310    AR  200300
  10428    AR   65600
  10441    AR   87600
  10568    AR  130100
  10577    AR  245400
  10600    AR  163400
  10655    AR  178100
  10659    AR  120400
  10771    AR  251000
  10783    AR   96900
  10793    AR  119400
  10815    AR  118400
  10819    AR  113300

  [82 rows x 2 columns]), ('AZ',       State   Price
  4        AZ  211300
  24       AZ  164800
  31       AZ  221400
  67       AZ  278200
  74       AZ  212600
  99       AZ  292900
  100      AZ  421200
  152      AZ  258600
  167      AZ  248100
  180      AZ  141200
  215      AZ  231500
  237      AZ  227400
  382      AZ  339700
  413      AZ  183200
  553      AZ  150000
  575      AZ  201200
  628      AZ  257900
  771      AZ  229500
  803      AZ  329600
  813      AZ  178000
  851      AZ  159600
  863      AZ  130700
  917      AZ  195600
  1175     AZ  278400
  1194     AZ  346400
  1232     AZ  156400
  1276     AZ  163900
  1381     AZ  235400
  1420     AZ  171700
  1539     AZ  424100
  ...     ...     ...
  6581     AZ  344600
  6749     AZ  251500
  7127     AZ  751100
  7198     AZ  274800
  7229     AZ  161000
  7405     AZ  148200
  7719     AZ  252200
  8363     AZ  470100
  8414     AZ   94200
  8612     AZ  218700
  8832     AZ   81500
  9001     AZ  133500
  9037     AZ  156500
  9110     AZ  235600
  9140     AZ  288800
  9288     AZ  212700
  9375     AZ  157800
  9472     AZ  276600
  9541     AZ  192800
  9705     AZ  186200
  9786     AZ  148500
  9824     AZ  139100
  9942     AZ  106800
  10192    AZ  251900
  10246    AZ  153600
  10298    AZ  317300
  10379    AZ  232800
  10410    AZ  288300
  10563    AZ  284900
  10587    AZ  247100

  [102 rows x 2 columns]), ('CA',       State    Price
  1        CA   629900
  6        CA   572100
  8        CA   877400
  10       CA  1194300
  29       CA   212700
  30       CA   299200
  32       CA   552700
  38       CA   680100
  49       CA   568800
  50       CA   509800
  55       CA   349900
  58       CA   219800
  65       CA   256100
  70       CA   260800
  83       CA   253300
  84       CA   436800
  85       CA   486900
  89       CA   348200
  94       CA   942400
  102      CA   793600
  105      CA   459000
  107      CA   533000
  114      CA   486700
  118      CA   772000
  123      CA   764400
  126      CA   431200
  128      CA   289500
  134      CA   245800
  139      CA   582800
  144      CA   387400
  ...     ...      ...
  10288    CA   158900
  10308    CA   270200
  10328    CA  1038600
  10364    CA   183700
  10367    CA   278400
  10406    CA   466800
  10419    CA   212200
  10421    CA   810100
  10435    CA   142400
  10456    CA   347700
  10470    CA   644200
  10490    CA   476600
  10514    CA   133000
  10515    CA   199600
  10517    CA   283700
  10538    CA  2604000
  10553    CA   470400
  10578    CA   219900
  10580    CA   279700
  10612    CA   831400
  10640    CA   720200
  10645    CA   204600
  10667    CA   535000
  10757    CA   283400
  10761    CA   283200
  10775    CA   360200
  10776    CA   509800
  10808    CA  1108300
  10810    CA   269700
  10817    CA  3173600

  [701 rows x 2 columns]), ('CO',       State   Price
  20       CO  383200
  35       CO  251200
  51       CO  286700
  135      CO  355300
  159      CO  138700
  177      CO  366200
  244      CO  321700
  246      CO  335000
  287      CO  203700
  340      CO  425300
  344      CO  368200
  349      CO  448400
  356      CO  235600
  401      CO  687000
  429      CO  312100
  437      CO  446000
  450      CO  343400
  770      CO  393800
  812      CO  446500
  1109     CO  409900
  1170     CO  308900
  1225     CO  313300
  1264     CO  359200
  1318     CO  335000
  1342     CO  290400
  1398     CO  226600
  1402     CO  215900
  1467     CO  398300
  1721     CO  383300
  1843     CO  405400
  ...     ...     ...
  9555     CO  191100
  9742     CO  363600
  9796     CO  279600
  9914     CO  205100
  10020    CO  155200
  10021    CO  232900
  10148    CO  319700
  10168    CO  217000
  10186    CO  238500
  10201    CO  125400
  10215    CO  180800
  10269    CO  217600
  10282    CO  976800
  10316    CO  251800
  10354    CO  170600
  10436    CO  215200
  10477    CO  226300
  10592    CO  289700
  10648    CO  279000
  10695    CO  238500
  10708    CO  249400
  10728    CO  246500
  10749    CO  275400
  10758    CO  325700
  10764    CO  274500
  10778    CO  268400
  10788    CO  504200
  10802    CO  418600
  10812    CO  350600
  10813    CO  300100

  [166 rows x 2 columns]), ('CT',       State    Price
  185      CT   164100
  206      CT   161200
  219      CT   100100
  220      CT   460300
  249      CT   107500
  403      CT   393800
  435      CT   261200
  493      CT   138900
  621      CT   293900
  652      CT   198700
  654      CT   174000
  659      CT   155800
  673      CT  1351300
  683      CT   168200
  767      CT   529800
  777      CT   167000
  853      CT   235600
  856      CT   278900
  868      CT   209800
  872      CT   151000
  944      CT   243800
  988      CT   172800
  1055     CT   165200
  1167     CT   305300
  1172     CT   138100
  1208     CT   357200
  1240     CT   321100
  1379     CT   211200
  1446     CT   168500
  1449     CT   289100
  ...     ...      ...
  7557     CT   151300
  7613     CT   216500
  7622     CT   195800
  7642     CT   322200
  7743     CT   428400
  7746     CT   234700
  7971     CT   259200
  7981     CT   263400
  7997     CT   574300
  8352     CT   362900
  8353     CT   212000
  8444     CT   142400
  8597     CT   336400
  8679     CT   422800
  8720     CT   427800
  8727     CT   214800
  8846     CT   280600
  8854     CT   440200
  8886     CT   240900
  8980     CT   275600
  9016     CT   340600
  9204     CT   310700
  9494     CT   190800
  9543     CT   220700
  9624     CT   330000
  9661     CT   591700
  9675     CT   175200
  9713     CT   358400
  10389    CT   230700
  10485    CT   704600

  [183 rows x 2 columns]), ('DC',    State   Price
  21    DC  555900), ('DE',       State   Price
  189      DE  223200
  519      DE  135500
  751      DE  178800
  1341     DE  161700
  1618     DE  256000
  1811     DE  217800
  2771     DE  213800
  3202     DE  415100
  3343     DE  255000
  3864     DE  176600
  4357     DE  173900
  4358     DE  200200
  5002     DE  157000
  5218     DE  148700
  5902     DE  168700
  6638     DE  164400
  7045     DE  213100
  8213     DE  172600
  9307     DE  206100
  9331     DE  178900
  9433     DE  126800
  9755     DE  152200
  9848     DE  168300
  10036    DE  144600
  10081    DE  412800
  10418    DE  332500), ('FL',       State    Price
  9        FL   152300
  37       FL   300500
  48       FL   184200
  64       FL   166900
  76       FL   167100
  78       FL   181100
  79       FL   132100
  87       FL   234700
  90       FL   202100
  104      FL   320300
  106      FL   223000
  115      FL   163500
  117      FL   126300
  130      FL   195600
  140      FL   287400
  161      FL   215100
  163      FL   279500
  172      FL   230200
  175      FL   240800
  214      FL   263900
  216      FL   331300
  250      FL   155000
  252      FL   209600
  281      FL   157300
  282      FL   205100
  285      FL   182400
  298      FL   228900
  299      FL   216000
  322      FL   166100
  323      FL   182700
  ...     ...      ...
  9913     FL  1719000
  9955     FL   178100
  9991     FL   753100
  10059    FL   245800
  10070    FL   128000
  10072    FL    96300
  10096    FL   247100
  10117    FL   263100
  10153    FL   163400
  10180    FL  4248200
  10205    FL  1382300
  10227    FL   367900
  10245    FL    90600
  10256    FL   168500
  10265    FL   507000
  10380    FL   913400
  10391    FL   181000
  10398    FL   132200
  10429    FL   168900
  10481    FL   110000
  10483    FL   153700
  10507    FL   506300
  10510    FL   294800
  10546    FL   283400
  10575    FL   523300
  10576    FL    89600
  10579    FL   484000
  10583    FL   389600
  10605    FL    62200
  10725    FL   235600

  [528 rows x 2 columns]), ('GA',       State   Price
  36       GA  208100
  56       GA  255900
  93       GA  187200
  111      GA   82000
  142      GA   88200
  207      GA  281800
  221      GA  119800
  254      GA  149300
  265      GA  160900
  289      GA  130900
  304      GA  149300
  316      GA  454500
  325      GA  221200
  331      GA   82500
  364      GA  117800
  366      GA  114300
  370      GA  166800
  400      GA  210300
  428      GA  199000
  432      GA  140700
  442      GA  117800
  443      GA  213400
  448      GA  360900
  451      GA  173900
  462      GA  134200
  484      GA   96900
  485      GA  126200
  494      GA   70400
  532      GA  233100
  540      GA  243300
  ...     ...     ...
  10177    GA  192200
  10209    GA  151300
  10257    GA  144400
  10281    GA   82700
  10301    GA  179300
  10306    GA  123200
  10324    GA  191400
  10329    GA  186100
  10413    GA   61200
  10430    GA   66200
  10503    GA  120000
  10525    GA  148700
  10530    GA  134900
  10567    GA   98300
  10602    GA  288300
  10604    GA  165000
  10629    GA  104800
  10638    GA  114600
  10660    GA   95600
  10661    GA  193200
  10668    GA  172200
  10679    GA  165300
  10692    GA   72800
  10705    GA  199300
  10720    GA  134500
  10741    GA  121000
  10772    GA  125600
  10787    GA   87000
  10811    GA  379900
  10814    GA  224900

  [266 rows x 2 columns]), ('HI',       State    Price
  41       HI   672900
  547      HI   633700
  687      HI   586500
  791      HI   688800
  810      HI   993000
  892      HI   804000
  921      HI   585100
  955      HI   310200
  1042     HI   624900
  1058     HI   680800
  1176     HI   396300
  1189     HI   686100
  1461     HI   562200
  1730     HI   606200
  1915     HI   612100
  1925     HI   489100
  2404     HI   170900
  2540     HI   683300
  2555     HI   647700
  3522     HI   273900
  3618     HI   838800
  4284     HI   780700
  4670     HI   728700
  4922     HI   385700
  5057     HI   644600
  5745     HI  1136400
  6051     HI   341800
  6397     HI   485100
  6715     HI   617100
  7283     HI   438900
  7383     HI   440700
  8089     HI   198500
  8108     HI   921800
  8622     HI   490000
  8724     HI   491100
  9386     HI   236300
  9697     HI   615700
  9933     HI   665400
  10149    HI   773600
  10293    HI   686400
  10412    HI   913500
  10493    HI   278800
  10719    HI   251600), ('IA',       State   Price
  108      IA  120300
  302      IA  131300
  537      IA  117600
  714      IA  208500
  1087     IA  212300
  1148     IA  225100
  1362     IA  149200
  1528     IA  126400
  2247     IA  173000
  2473     IA  239200
  2836     IA  266300
  2912     IA  265700
  3034     IA  191300
  4160     IA  221300
  4212     IA  183700
  4274     IA  182600
  4598     IA  218600
  4820     IA  260000
  5162     IA  101300
  5307     IA  122900
  5657     IA  183200
  5894     IA  139700
  6425     IA  220200
  6438     IA  171400
  6452     IA  107600
  6909     IA  235900
  7182     IA  242100
  7203     IA  170100
  7234     IA   95600
  7242     IA  181700
  ...     ...     ...
  8184     IA  185700
  8249     IA   94700
  8306     IA  121000
  8316     IA  156100
  8465     IA  115600
  8525     IA  129000
  8615     IA  155300
  8956     IA  149200
  8966     IA  104000
  9010     IA   99900
  9064     IA  177500
  9243     IA  117000
  9371     IA  202200
  9384     IA  175800
  9549     IA  162500
  9592     IA  140500
  9606     IA  190800
  9628     IA  218700
  9664     IA  114200
  9772     IA  318200
  9826     IA  131700
  9833     IA  235100
  9948     IA  201600
  10015    IA  191300
  10028    IA  235300
  10330    IA  148000
  10423    IA  222500
  10502    IA  152500
  10675    IA  205300
  10779    IA  258400

  [63 rows x 2 columns]), ('ID',       State   Price
  119      ID  213700
  275      ID  155100
  359      ID  227200
  934      ID  154500
  1069     ID  140000
  1217     ID  145800
  1297     ID  179700
  1416     ID  175100
  2456     ID  136500
  2641     ID  349900
  2725     ID  175300
  2948     ID  219100
  3890     ID  169600
  4118     ID  138800
  4868     ID  219500
  5328     ID  209700
  5381     ID  179000
  6220     ID  237900
  6658     ID  179700
  6683     ID  150400
  6817     ID  184300
  7361     ID  128300
  8683     ID  219300
  9067     ID  164300
  9773     ID  140800
  9921     ID  166300
  10226    ID  129100
  10278    ID  146800
  10303    ID  209900
  10545    ID  130600
  10588    ID  218500
  10618    ID  330800
  10782    ID  177400), ('IL',       State   Price
  2        IL  222700
  125      IL   80500
  143      IL  169700
  166      IL  380400
  227      IL  133300
  241      IL  105800
  261      IL   88300
  354      IL  140100
  358      IL  174900
  396      IL  158400
  460      IL  151300
  473      IL  327400
  480      IL  331600
  488      IL  113800
  533      IL  229600
  565      IL  228800
  585      IL  252100
  614      IL  212200
  630      IL  267700
  634      IL  246100
  685      IL  182800
  692      IL  286300
  703      IL  197100
  761      IL  328900
  774      IL  303300
  790      IL  369600
  809      IL  211200
  834      IL  121800
  885      IL  252700
  894      IL  321100
  ...     ...     ...
  10321    IL  479000
  10335    IL   58900
  10343    IL  182800
  10347    IL  102600
  10361    IL  147600
  10366    IL  149500
  10392    IL   69000
  10403    IL  154300
  10414    IL   64000
  10446    IL  134100
  10484    IL  126800
  10492    IL   63700
  10500    IL  265700
  10508    IL   92900
  10511    IL  172700
  10526    IL   50200
  10533    IL  115600
  10537    IL  116900
  10555    IL   84400
  10572    IL  131800
  10596    IL   75100
  10598    IL  123900
  10609    IL  248300
  10639    IL   94400
  10684    IL   97100
  10693    IL  228100
  10703    IL  132800
  10704    IL   66600
  10742    IL  135300
  10753    IL  205500

  [496 rows x 2 columns]), ('IN',       State   Price
  80       IN  102100
  137      IN  108800
  212      IN  169000
  343      IN   65000
  363      IN   75000
  371      IN   75100
  373      IN  112800
  407      IN   52800
  472      IN  162700
  498      IN  190900
  528      IN   78500
  568      IN  177100
  577      IN   81500
  587      IN  100600
  627      IN  138900
  647      IN  301100
  749      IN  178100
  823      IN  135700
  855      IN   54800
  936      IN  126200
  945      IN  134300
  974      IN   74100
  1051     IN   63800
  1084     IN  124200
  1160     IN  216000
  1244     IN  141000
  1323     IN  167700
  1440     IN  170700
  1460     IN  125300
  1531     IN  109300
  ...     ...     ...
  10323    IN   79300
  10325    IN   72600
  10326    IN  114000
  10333    IN   80700
  10344    IN   95000
  10374    IN  134700
  10439    IN  103700
  10463    IN   78200
  10487    IN  139000
  10496    IN   80300
  10501    IN  139000
  10540    IN  109200
  10593    IN   67600
  10622    IN   77600
  10641    IN   84000
  10651    IN   74200
  10662    IN   77700
  10669    IN  147300
  10671    IN  162900
  10677    IN  175100
  10683    IN  110900
  10687    IN  114500
  10699    IN  100000
  10718    IN  104300
  10729    IN  121400
  10736    IN   76800
  10767    IN  138500
  10784    IN  104900
  10809    IN   82200
  10821    IN  157700

  [418 rows x 2 columns]), ('KS',       State   Price
  47       KS  121500
  148      KS  262600
  157      KS   94700
  171      KS   78800
  213      KS  224400
  333      KS  175500
  649      KS  226500
  869      KS  251600
  884      KS  104800
  1262     KS  138600
  1453     KS  424900
  1574     KS  172600
  2001     KS  238600
  2057     KS  186400
  3460     KS  121700
  3511     KS  166600
  4459     KS  163700
  4645     KS  144700
  4704     KS  215600
  4717     KS  203700
  4920     KS  156700
  4948     KS  177600
  5276     KS  176700
  5353     KS  167700
  5968     KS  171500
  5983     KS  162700
  6433     KS  193400
  6612     KS  804100
  6691     KS  165000
  6721     KS  174700
  6849     KS   97300
  7161     KS   52100
  7296     KS  139900
  7441     KS  120500
  7721     KS   61300
  7760     KS  135200
  8100     KS  142000
  8109     KS  103000
  8118     KS  154300
  8672     KS  445000
  8747     KS  184800
  8779     KS   70800
  8868     KS  123800
  8910     KS   78900
  9058     KS  153500
  9125     KS  146300
  9484     KS  192200
  9679     KS  357200
  9757     KS  152600
  9943     KS  166800
  10026    KS  142600
  10462    KS  137700), ('KY',       State   Price
  62       KY  164800
  68       KY  116600
  295      KY  167200
  713      KY  158200
  901      KY  131100
  1029     KY  145800
  1044     KY  114800
  1091     KY  177700
  1101     KY  137500
  1202     KY   97700
  1490     KY  115800
  1631     KY  142000
  1743     KY  173200
  1851     KY  127400
  2052     KY  172300
  2179     KY  174200
  2243     KY   85300
  2265     KY  122600
  2420     KY  235700
  2432     KY  165600
  2646     KY  193500
  2665     KY  100100
  2681     KY  118800
  2785     KY  150100

## Apply a function on each group and combine the results

In [10]:
grouped_data.mean().head()

        Price
State
AK     237783
AL     137645
AR     136331
AZ     232353
CA     617425

## Get Descriptive statistics by Groups(States)

In [11]:
grouped_data.describe()

                    Price
State
AK    count  1.200000e+01
      mean   2.377833e+05
      std    4.143371e+04
      min    1.758000e+05
      25%    2.117000e+05
      50%    2.228500e+05
      75%    2.549500e+05
      max    3.231000e+05
AL    count  1.490000e+02
      mean   1.376456e+05
      std    7.253854e+04
      min    4.470000e+04
      25%    1.039000e+05
      50%    1.264000e+05
      75%    1.558000e+05
      max    5.989000e+05
AR    count  8.200000e+01
      mean   1.363317e+05
      std    4.237054e+04
      min    6.530000e+04
      25%    1.081750e+05
      50%    1.287500e+05
      75%    1.550500e+05
      max    2.688000e+05
AZ    count  1.020000e+02
      mean   2.323539e+05
      std    1.730686e+05
      min    8.150000e+04
      25%    1.488750e+05
      50%    2.119500e+05
...                   ...
WA    std    2.822708e+05
      min    9.570000e+04
      25%    2.055500e+05
      50%    2.822000e+05
      75%    3.674500e+05
      max    2.556000e+06
WI    count  2.700000e+02
      mean   2.101959e+05
      std    7.310966e+04
      min    7.050000e+04
      25%    1.584000e+05
      50%    1.937000e+05
      75%    2.551250e+05
      max    6.420000e+05
WV    count  1.700000e+01
      mean   9.032941e+04
      std    1.791256e+04
      min    6.810000e+04
      25%    7.370000e+04
      50%    8.960000e+04
      75%    1.002000e+05
      max    1.232000e+05
WY    count  1.000000e+01
      mean   1.991700e+05
      std    4.352062e+04
      min    1.521000e+05
      25%    1.761250e+05
      50%    1.924000e+05
      75%    2.049000e+05
      max    3.061000e+05

[392 rows x 1 columns]

## Group by data on State and Region

In [16]:
grouped_data = data[['State',
                     'RegionName', 
                     'Price']].groupby(['State','RegionName']).mean()
grouped_data.head()

                     Price
State RegionName
AK    Anchor Point  175800
      Anchorage     293900
      Fairbanks     221000
      Juneau        323100
      Kenai         206500

## Get the number of records per State

In [13]:
grouped_data = data.groupby(['State']).size()
grouped_data

State
AK      12
AL     149
AR      82
AZ     102
CA     701
CO     166
CT     183
DC       1
DE      26
FL     528
GA     266
HI      43
IA      63
ID      33
IL     496
IN     418
KS      52
KY     118
LA     148
MA     334
MD     318
ME       1
MI     461
MN     155
MO     202
MS     135
MT      20
NC     293
ND      12
NE      20
NH     190
NJ     577
NM      26
NV      26
NY     717
OH     507
OK      70
OR     164
PA    1208
RI      41
SC     138
TN     350
TX     397
UT      81
VA     228
WA     275
WI     270
WV      17
WY      10
dtype: int64

## Group by Columns

In [14]:
grouped_data = data.groupby(data.dtypes, axis=1)
list(grouped_data)

[(dtype('int64'),        RegionID  SizeRank    Price
  0          6181         0   672400
  1         12447         1   629900
  2         17426         2   222700
  3         13271         3   137300
  4         40326         4   211300
  5         18959         5   216500
  6         54296         6   572100
  7         38128         7   164700
  8         33839         8   877400
  9         25290         9   152300
  10        20330        10  1194300
  11        10221        11   321600
  12        17762        12    41500
  13        10920        13   128300
  14        32811        14    81100
  15        24043        15   183800
  16        17933        16   113400
  17        44269        17   554600
  18        16037        18   670300
  19         3523        19   121100
  20        11093        20   383200
  21        41568        21   555900
  22         6118        22   228500
  23         5976        23   107900
  24         7481        24   164800
  25        13373        25   417900
  26        33225        26   132700
  27        40152        27   152100
  28        23429        28   189600
  29        18203        29   212700
  ...         ...       ...      ...
  10800     36944     10800   237500
  10801     44501     10801    73700
  10802     44615     10802   418600
  10803     44844     10803   264800
  10804     49693     10804   308000
  10805     50692     10805   137400
  10806    171874     10806   149000
  10807      7512     10807   105600
  10808      8646     10808  1108300
  10809     13137     10809    82200
  10810     25468     10810   269700
  10811     25749     10811   379900
  10812     25835     10812   350600
  10813     32017     10813   300100
  10814     32847     10814   224900
  10815     46172     10815   118400
  10816     46452     10816   146800
  10817     49856     10817  3173600
  10818     54802     10818  1958600
  10819     55357     10819   113300
  10820      5216     10820   256700
  10821     12312     10821   157700
  10822     18317     10822   175700
  10823     19929     10823   122600
  10824     22147     10824   106200
  10825     26077     10825   392200
  10826     24105     10826   191900
  10827    737788     10827   231100
  10828    182023     10828   230800
  10829     51793     10829   296400

  [10830 rows x 3 columns]),
 (dtype('O'),
               Date         RegionName State                           Metro  \
  0      2017-05-31           New York    NY                        New York
  1      2017-05-31        Los Angeles    CA  Los Angeles-Long Beach-Anaheim
  2      2017-05-31            Chicago    IL                         Chicago
  3      2017-05-31       Philadelphia    PA                    Philadelphia
  4      2017-05-31            Phoenix    AZ                         Phoenix
  5      2017-05-31          Las Vegas    NV                       Las Vegas
  6      2017-05-31          San Diego    CA                       San Diego
  7      2017-05-31             Dallas    TX               Dallas-Fort Worth
  8      2017-05-31           San Jose    CA                        San Jose
  9      2017-05-31       Jacksonville    FL                    Jacksonville
  10     2017-05-31      San Francisco    CA                   San Francisco
  11     2017-05-31             Austin    TX                          Austin
  12     2017-05-31            Detroit    MI                         Detroit
  13     2017-05-31           Columbus    OH                        Columbus
  14     2017-05-31            Memphis    TN                         Memphis
  15     2017-05-31          Charlotte    NC                       Charlotte
  16     2017-05-31            El Paso    TX                         El Paso
  17     2017-05-31             Boston    MA                          Boston
  18     2017-05-31            Seattle    WA                         Seattle
  19     2017-05-31          Baltimore    MD                       Baltimore
  20     2017-05-31             Denver    CO                          Denver
  21     2017-05-31         Washington    DC                      Washington
  22     2017-05-31          Nashville    TN                       Nashville
  23     2017-05-31          Milwaukee    WI                       Milwaukee
  24     2017-05-31             Tucson    AZ                          Tucson
  25     2017-05-31           Portland    OR                        Portland
  26     2017-05-31      Oklahoma City    OK                   Oklahoma City
  27     2017-05-31              Omaha    NE                           Omaha
  28     2017-05-31        Albuquerque    NM                     Albuquerque
  29     2017-05-31             Fresno    CA                          Fresno
  ...           ...                ...   ...                             ...
  10800  2017-05-31       Mount Sidney    VA                        Staunton
  10801  2017-05-31        Cedar Grove    WV                      Charleston
  10802  2017-05-31              Clark    CO               Steamboat Springs
  10803  2017-05-31          Daleville    VA                         Roanoke
  10804  2017-05-31        Piney Point    MD       California-Lexington Park
  10805  2017-05-31               Almo    KY                          Murray
  10806  2017-05-31         Bois D Arc    MO                     Springfield
  10807  2017-05-31            Tyaskin    MD                       Salisbury
  10808  2017-05-31          Inverness    CA                   San Francisco
  10809  2017-05-31             Otwell    IN                          Jasper
  10810  2017-05-31        Lake Hughes    CA  Los Angeles-Long Beach-Anaheim
  10811  2017-05-31        Marble Hill    GA                         Atlanta
  10812  2017-05-31               Mead    CO                         Greeley
  10813  2017-05-31           Hesperus    CO                         Durango
  10814  2017-05-31            Midland    GA                        Columbus
  10815  2017-05-31             Lavaca    AR                      Fort Smith
  10816  2017-05-31       Mays Landing    NJ                   Atlantic City
  10817  2017-05-31      Stinson Beach    CA                   San Francisco
  10818  2017-05-31   Upper Brookville    NY                        New York
  10819  2017-05-31            Decatur    AR                    Fayetteville
  10820  2017-05-31         Horse Shoe    NC                       Asheville
  10821  2017-05-31             Laotto    IN                    Kendallville
  10822  2017-05-31          Goldsboro    MD                             NaN
  10823  2017-05-31          Phoenicia    NY                        Kingston
  10824  2017-05-31              Jones    AL                      Montgomery
  10825  2017-05-31            Nehalem    OR                             NaN
  10826  2017-05-31  Clear Lake Shores    TX                         Houston
  10827  2017-05-31    Lebanon Borough    NJ                        New York
  10828  2017-05-31            Henrico    VA                        Richmond
  10829  2017-05-31     East Hampstead    NH                          Boston

                       County
  0                    Queens
  1               Los Angeles
  2                      Cook
  3              Philadelphia
  4                  Maricopa
  5                     Clark
  6                 San Diego
  7                    Dallas
  8               Santa Clara
  9                     Duval
  10            San Francisco
  11                   Travis
  12                    Wayne
  13                 Franklin
  14                   Shelby
  15              Mecklenburg
  16                  El Paso
  17                  Suffolk
  18                     King
  19           Baltimore City
  20                   Denver
  21     District of Columbia
  22                 Davidson
  23                Milwaukee
  24                     Pima
  25                Multnomah
  26                 Oklahoma
  27                  Douglas
  28               Bernalillo
  29                   Fresno
  ...                     ...
  10800               Augusta
  10801               Kanawha
  10802                 Routt
  10803             Botetourt
  10804           Saint Marys
  10805              Calloway
  10806                Greene
  10807              Wicomico
  10808                 Marin
  10809                  Pike
  10810           Los Angeles
  10811                Dawson
  10812                  Weld
  10813              La Plata
  10814              Muscogee
  10815             Sebastian
  10816              Atlantic
  10817                 Marin
  10818                Nassau
  10819                Benton
  10820             Henderson
  10821                 Noble
  10822              Caroline
  10823                Ulster
  10824               Autauga
  10825             Tillamook
  10826             Galveston
  10827             Hunterdon
  10828               Henrico
  10829            Rockingham

  [10830 rows x 5 columns])]

## Iterate over Groups

In [15]:
for state, grouped_data in data.groupby('State'):
    print(state, '\n', grouped_data)

AK
              Date  RegionID    RegionName State      Metro  \
57     2017-05-31     23482     Anchorage    AK  Anchorage
842    2017-05-31     38465     Fairbanks    AK  Fairbanks
1793   2017-05-31     36906        Palmer    AK  Anchorage
1830   2017-05-31     29910    North Pole    AK  Fairbanks
1974   2017-05-31      5365        Juneau    AK     Juneau
3756   2017-05-31     52742         Kenai    AK        NaN
3869   2017-05-31     39281        Kodiak    AK        NaN
4450   2017-05-31    102611       Tanaina    AK  Anchorage
5229   2017-05-31     32296     Ketchikan    AK  Ketchikan
5996   2017-05-31    395445         Lakes    AK  Anchorage
9622   2017-05-31     54367        Seward    AK        NaN
10162  2017-05-31     28124  Anchor Point    AK        NaN

                     County  SizeRank   Price
57                Anchorage        57  293900
842    Fairbanks North Star       842  221000
1793      Matanuska Susitna      1793  247800
1830   Fairbanks North Star      1830  213100
1974                 Juneau      1974  323100
3756        Kenai Peninsula      3756  206500
3869          Kodiak Island      3869  270700
4450      Matanuska Susitna      4450  224700
5229      Ketchikan Gateway      5229  207500
5996      Matanuska Susitna      5996  249700
9622        Kenai Peninsula      9622  219600
10162       Kenai Peninsula     10162  175800
AL
              Date  RegionID         RegionName State       Metro       County  \
71     2017-05-31     32900             Mobile    AL      Mobile       Mobile
121    2017-05-31     10417         Birmingham    AL  Birmingham    Jefferson
154    2017-05-31     12014         Huntsville    AL  Huntsville      Madison
736    2017-05-31     11455           Florence    AL    Florence   Lauderdale
913    2017-05-31      4317            Decatur    AL     Decatur       Morgan
1010   2017-05-31     54001         Prattville    AL  Montgomery      Autauga
1035   2017-05-31     25179             Hoover    AL  Birmingham    Jefferson
1254   2017-05-31     18225            Gadsden    AL     Gadsden       Etowah
1356   2017-05-31     25704            Madison    AL  Huntsville      Madison
1577   2017-05-31      4660           Fairhope    AL      Daphne      Baldwin
1705   2017-05-31     43839          Alabaster    AL  Birmingham       Shelby
1961   2017-05-31     26624           Prichard    AL      Mobile       Mobile
2023   2017-05-31     41216           Theodore    AL      Mobile       Mobile
2109   2017-05-31     14948             Daphne    AL      Daphne      Baldwin
2121   2017-05-31     45794           Homewood    AL  Birmingham    Jefferson
2157   2017-05-31     16997           Bessemer    AL  Birmingham    Jefferson
2237   2017-05-31     35744          Hartselle    AL     Decatur       Morgan
2268   2017-05-31     24739              Foley    AL      Daphne      Baldwin
2287   2017-05-31     14382     Vestavia Hills    AL  Birmingham    Jefferson
2393   2017-05-31     52663       Jacksonville    AL    Anniston      Calhoun
2399   2017-05-31     34362          Tuscumbia    AL    Florence      Colbert
2410   2017-05-31     23492           Anniston    AL    Anniston      Calhoun
2494   2017-05-31     26049      Muscle Shoals    AL    Florence      Colbert
2659   2017-05-31     53849          Pell City    AL  Birmingham  Saint Clair
2716   2017-05-31     16172         Trussville    AL  Birmingham    Jefferson
2789   2017-05-31     26027     Mountain Brook    AL  Birmingham    Jefferson
2955   2017-05-31     42732             Pelham    AL  Birmingham       Shelby
3060   2017-05-31     11667          Grand Bay    AL      Mobile       Mobile
3078   2017-05-31      3562        Bay Minette    AL      Daphne      Baldwin
3112   2017-05-31     35381             Helena    AL  Birmingham       Shelby
...           ...       ...                ...   ...         ...          ...
9768   2017-05-31    102808               Argo    AL  Birmingham  Saint Clair
9790   2017-05-31     43396           Anderson    AL    Florence   Lauderdale
9794   2017-05-31     19472             Morris    AL  Birmingham    Jefferson
9821   2017-05-31      9754           Stockton    AL      Daphne      Baldwin
9857   2017-05-31      5803            Marbury    AL  Montgomery      Autauga
9864   2017-05-31      3460            Ashford    AL      Dothan      Houston
9866   2017-05-31     10284     Bayou La Batre    AL      Mobile       Mobile
9889   2017-05-31     47063            Perdido    AL      Daphne      Baldwin
9903   2017-05-31     57092               Clay    AL  Birmingham    Jefferson
9938   2017-05-31     51002        Billingsley    AL  Montgomery      Autauga
9960   2017-05-31     21823           Kimberly    AL  Birmingham    Jefferson
10023  2017-05-31     37993            Concord    AL  Birmingham    Jefferson
10037  2017-05-31     41048          Stapleton    AL      Daphne      Baldwin
10079  2017-05-31     33937           Seminole    AL      Daphne      Baldwin
10114  2017-05-31     43097     Sylvan Springs    AL  Birmingham    Jefferson
10115  2017-05-31     37845            Chelsea    AL  Birmingham       Shelby
10155  2017-05-31     56324          Riverside    AL  Birmingham  Saint Clair
10352  2017-05-31    106333         Priceville    AL     Decatur       Morgan
10362  2017-05-31    104022          Edgewater    AL  Birmingham    Jefferson
10369  2017-05-31     51655     Dauphin Island    AL      Mobile       Mobile
10370  2017-05-31     53438        Mount Olive    AL  Birmingham    Jefferson
10425  2017-05-31     10989             Creola    AL      Mobile       Mobile
10464  2017-05-31     22246              Mulga    AL  Birmingham    Jefferson
10491  2017-05-31      7377             Taylor    AL      Dothan      Houston
10504  2017-05-31    105442    McDonald Chapel    AL  Birmingham    Jefferson
10505  2017-05-31    105559              Minor    AL  Birmingham    Jefferson
10608  2017-05-31      6720           Rehobeth    AL      Dothan      Houston
10743  2017-05-31     26348  Owens Cross Roads    AL  Huntsville      Madison
10790  2017-05-31     15563       Mount Vernon    AL      Mobile       Mobile
10824  2017-05-31     22147              Jones    AL  Montgomery      Autauga

       SizeRank   Price
71           71  112100
121         121   61900
154         154  138600
736         736  110500
913         913  105700
1010       1010  141600
1035       1035  260300
1254       1254   66600
1356       1356  198300
1577       1577  267300
1705       1705  162100
1961       1961   48100
2023       2023  113200
2109       2109  180100
2121       2121  313900
2157       2157   58700
2237       2237  125300
2268       2268  161800
2287       2287  332900
2393       2393  109300
2399       2399  105900
2410       2410   64700
2494       2494  135700
2659       2659  148500
2716       2716  225400
2789       2789  598900
2955       2955  180800
3060       3060  125900
3078       3078  125700
3112       3112  176100
...         ...     ...
9768       9768  186200
9790       9790  111800
9794       9794  155800
9821       9821  130400
9857       9857  117700
9864       9864  124100
9866       9866   57200
9889       9889  110400
9903       9903  144800
9938       9938  110300
9960       9960  158700
10023     10023  107300
10037     10037  159500
10079     10079  184300
10114     10114  127100
10115     10115  221800
10155     10155  179400
10352     10352  161900
10362     10362   46600
10369     10369  271000
10370     10370  146600
10425     10425  122800
10464     10464   46000
10491     10491  100300
10504     10504   48800
10505     10505   62700
10608     10608  151500
10743     10743  132700
10790     10790   67000
10824     10824  106200

[149 rows x 8 columns]
AR
              Date  RegionID           RegionName State         Metro  \
129    2017-05-31     52998          Little Rock    AR   Little Rock
453    2017-05-31     38583           Fort Smith    AR    Fort Smith
489    2017-05-31     38004               Conway    AR   Little Rock
581    2017-05-31     18765            Jonesboro    AR     Jonesboro
588    2017-05-31     40057    North Little Rock    AR   Little Rock
660    2017-05-31     31543         Fayetteville    AR  Fayetteville
669    2017-05-31      7217           Springdale    AR  Fayetteville
879    2017-05-31     19944           Pine Bluff    AR    Pine Bluff
987    2017-05-31     26820               Rogers    AR  Fayetteville
1236   2017-05-31     52580          Hot Springs    AR   Hot Springs
1317   2017-05-31     12087         Jacksonville    AR   Little Rock
1339   2017-05-31      7668            Van Buren    AR    Fort Smith
1647   2017-05-31     20468             Sherwood    AR   Little Rock
1720   2017-05-31     50967               Benton    AR   Little Rock
1819   2017-05-31     50946          Bella Vista    AR  Fayetteville
1877   2017-05-31     19837            Paragould    AR     Paragould
2067   2017-05-31      7074       Siloam Springs    AR  Fayetteville
2126   2017-05-31     16989          Bentonville    AR  Fayetteville
2416   2017-05-31      3862               Bryant    AR   Little Rock
2648   2017-05-31     12678                 Mena    AR           NaN
2728   2017-05-31     14613           White Hall    AR    Pine Bluff
2784   2017-05-31     39048  Hot Springs Village    AR   Little Rock
2816   2017-05-31     53198             Maumelle    AR   Little Rock
3187   2017-05-31     31870            Greenwood    AR    Fort Smith
4590   2017-05-31     37304              Bauxite    AR   Little Rock
4665   2017-05-31     53996        Prairie Grove    AR  Fayetteville
4694   2017-05-31     39577              Malvern    AR       Malvern
4970   2017-05-31     17358            Centerton    AR  Fayetteville
5531   2017-05-31     47036            Pea Ridge    AR  Fayetteville
5738   2017-05-31     34737            West Fork    AR  Fayetteville
...           ...       ...                  ...   ...           ...
8199   2017-05-31      9533                Salem    AR   Little Rock
8368   2017-05-31     56989            Traskwood    AR   Little Rock
8583   2017-05-31     26710             Redfield    AR    Pine Bluff
8634   2017-05-31     45553           Greenbrier    AR   Little Rock
8678   2017-05-31     48276              Vilonia    AR   Little Rock
8690   2017-05-31      6821               Roland    AR   Little Rock
8829   2017-05-31     39830              Monette    AR     Jonesboro
8876   2017-05-31     14158            Tontitown    AR  Fayetteville
9266   2017-05-31     40849        Shannon Hills    AR   Little Rock
9639   2017-05-31      8724              Johnson    AR  Fayetteville
9723   2017-05-31     25060              Haskell    AR   Little Rock
9863   2017-05-31     54343                Scott    AR   Little Rock
9922   2017-05-31     51245      Cammack Village    AR   Little Rock
9992   2017-05-31     28529               Gentry    AR  Fayetteville
10126  2017-05-31     57039      Sulphur Springs    AR  Fayetteville
10185  2017-05-31     47006                Paron    AR   Little Rock
10218  2017-05-31      6085         Mount Vernon    AR   Little Rock
10310  2017-05-31    109470         Little Flock    AR  Fayetteville
10428  2017-05-31     14065           Sweet Home    AR   Little Rock
10441  2017-05-31      3560                  Bay    AR     Jonesboro
10568  2017-05-31      4555               Elkins    AR  Fayetteville
10577  2017-05-31     55355         Cave Springs    AR  Fayetteville
10600  2017-05-31     50991       Bethel Heights    AR  Fayetteville
10655  2017-05-31     31702             Garfield    AR  Fayetteville
10659  2017-05-31     47476                 Rudy    AR    Fort Smith
10771  2017-05-31     31412          Elm Springs    AR  Fayetteville
10783  2017-05-31     53456         Mountainburg    AR    Fort Smith
10793  2017-05-31     23234           Huntington    AR    Fort Smith
10815  2017-05-31     46172               Lavaca    AR    Fort Smith
10819  2017-05-31     55357              Decatur    AR  Fayetteville

           County  SizeRank   Price
129       Pulaski       129  132200
453     Sebastian       453  111500
489      Faulkner       489  143800
581     Craighead       581  133600
588       Pulaski       588   90600
660    Washington       660  186200
669    Washington       669  146600
879     Jefferson       879   72300
987        Benton       987  168200
1236      Garland      1236  111100
1317      Pulaski      1317   93500
1339     Crawford      1339  104600
1647      Pulaski      1647  136100
1720       Saline      1720  126500
1819       Benton      1819  162400
1877       Greene      1877  105400
2067       Benton      2067  139100
2126       Benton      2126  187700
2416       Saline      2416  150700
2648         Polk      2648  106500
2728    Jefferson      2728   95600
2784       Saline      2784  176300
2816      Pulaski      2816  198300
3187    Sebastian      3187  127400
4590       Saline      4590  138500
4665   Washington      4665  148300
4694   Hot Spring      4694   65300
4970       Benton      4970  152200
5531       Benton      5531  137700
5738   Washington      5738  139900
...           ...       ...     ...
8199       Saline      8199  130400
8368       Saline      8368  107200
8583    Jefferson      8583  121200
8634     Faulkner      8634  124300
8678     Faulkner      8678  138000
8690      Pulaski      8690  166300
8829    Craighead      8829   88800
8876   Washington      8876  268800
9266       Saline      9266  121900
9639   Washington      9639  169800
9723       Saline      9723  121600
9863      Pulaski      9863  159600
9922      Pulaski      9922  189000
9992       Benton      9992  118900
10126      Benton     10126  102400
10185      Saline     10185  156300
10218    Faulkner     10218  119700
10310      Benton     10310  200300
10428     Pulaski     10428   65600
10441   Craighead     10441   87600
10568  Washington     10568  130100
10577      Benton     10577  245400
10600      Benton     10600  163400
10655      Benton     10655  178100
10659    Crawford     10659  120400
10771  Washington     10771  251000
10783    Crawford     10783   96900
10793   Sebastian     10793  119400
10815   Sebastian     10815  118400
10819      Benton     10819  113300

[82 rows x 8 columns]
AZ
              Date  RegionID          RegionName State             Metro  \
4      2017-05-31     40326             Phoenix    AZ           Phoenix
24     2017-05-31      7481              Tucson    AZ            Tucson
31     2017-05-31     19331                Mesa    AZ           Phoenix
67     2017-05-31     17384            Chandler    AZ           Phoenix
74     2017-05-31     18298            Glendale    AZ           Phoenix
99     2017-05-31      4888             Gilbert    AZ           Phoenix
100    2017-05-31     54346          Scottsdale    AZ           Phoenix
152    2017-05-31     47958               Tempe    AZ           Phoenix
167    2017-05-31     40298              Peoria    AZ           Phoenix
180    2017-05-31     28065                Yuma    AZ              Yuma
215    2017-05-31      8814         Queen Creek    AZ           Phoenix
237    2017-05-31      7330            Surprise    AZ           Phoenix
382    2017-05-31     31567           Flagstaff    AZ         Flagstaff
413    2017-05-31    737787      San Tan Valley    AZ           Phoenix
553    2017-05-31     10727         Casa Grande    AZ           Phoenix
575    2017-05-31     10226            Avondale    AZ           Phoenix
628    2017-05-31     18329            Goodyear    AZ           Phoenix
771    2017-05-31     46105    Lake Havasu City    AZ  Lake Havasu City
803    2017-05-31     26620            Prescott    AZ          Prescott
813    2017-05-31     32697            Maricopa    AZ           Phoenix
851    2017-05-31    192040        Sierra Vista    AZ      Sierra Vista
863    2017-05-31     46039             Kingman    AZ  Lake Havasu City
917    2017-05-31      3869             Buckeye    AZ           Phoenix
1175   2017-05-31     26329          Oro Valley    AZ            Tucson
1194   2017-05-31      3418              Anthem    AZ           Phoenix
1232   2017-05-31     41130            Sun City    AZ           Phoenix
1276   2017-05-31     30651       Bullhead City    AZ  Lake Havasu City
1381   2017-05-31     54002     Prescott Valley    AZ          Prescott
1420   2017-05-31     11278           El Mirage    AZ           Phoenix
1539   2017-05-31    111627  Catalina Foothills    AZ            Tucson
...           ...       ...                 ...   ...               ...
6581   2017-05-31     26113           New River    AZ           Phoenix
6749   2017-05-31     21624           Clarkdale    AZ          Prescott
7127   2017-05-31     23952            Carefree    AZ           Phoenix
7198   2017-05-31     31051           Cornville    AZ          Prescott
7229   2017-05-31     13111              Oracle    AZ           Phoenix
7405   2017-05-31     34971               Amado    AZ            Tucson
7719   2017-05-31     33354             Paulden    AZ          Prescott
8363   2017-05-31     40575           Rio Verde    AZ           Phoenix
8414   2017-05-31     13233              Pearce    AZ      Sierra Vista
8612   2017-05-31     56350                Pine    AZ            Payson
8832   2017-05-31      5381              Kearny    AZ           Phoenix
9001   2017-05-31     14747           Youngtown    AZ           Phoenix
9037   2017-05-31     29116                Pima    AZ           Safford
9110   2017-05-31     33347           Patagonia    AZ           Nogales
9140   2017-05-31     21021                Vail    AZ            Tucson
9288   2017-05-31     17586    Corona de Tucson    AZ            Tucson
9375   2017-05-31     12620               Mayer    AZ          Prescott
9472   2017-05-31    396566      Dewey-Humboldt    AZ          Prescott
9541   2017-05-31     55723            Kirkland    AZ          Prescott
9705   2017-05-31     30475   Black Canyon City    AZ          Prescott
9786   2017-05-31     54520       Springerville    AZ               NaN
9824   2017-05-31     17846               Eagar    AZ               NaN
9942   2017-05-31     27433           Tombstone    AZ      Sierra Vista
10192  2017-05-31     36601          Happy Jack    AZ         Flagstaff
10246  2017-05-31     16202         Saint David    AZ      Sierra Vista
10298  2017-05-31     29566             Sonoita    AZ           Nogales
10379  2017-05-31    112945         Star Valley    AZ            Payson
10410  2017-05-31      8875          Munds Park    AZ         Flagstaff
10563  2017-05-31     14196               Tubac    AZ           Nogales
10587  2017-05-31     35704        Forest Lakes    AZ         Flagstaff

           County  SizeRank   Price
4        Maricopa         4  211300
24           Pima        24  164800
31       Maricopa        31  221400
67       Maricopa        67  278200
74       Maricopa        74  212600
99       Maricopa        99  292900
100      Maricopa       100  421200
152      Maricopa       152  258600
167      Maricopa       167  248100
180          Yuma       180  141200
215      Maricopa       215  231500
237      Maricopa       237  227400
382      Coconino       382  339700
413         Pinal       413  183200
553         Pinal       553  150000
575      Maricopa       575  201200
628      Maricopa       628  257900
771        Mohave       771  229500
803       Yavapai       803  329600
813         Pinal       813  178000
851       Cochise       851  159600
863        Mohave       863  130700
917      Maricopa       917  195600
1175         Pima      1175  278400
1194     Maricopa      1194  346400
1232     Maricopa      1232  156400
1276       Mohave      1276  163900
1381      Yavapai      1381  235400
1420     Maricopa      1420  171700
1539         Pima      1539  424100
...           ...       ...     ...
6581     Maricopa      6581  344600
6749      Yavapai      6749  251500